### ISSUE TITLE
This is a waste of time.

### ISSUE THREAD

**Issue by ghost** [sonicdcer/sf64#262]
Imagine trying to decompile a children's game consisting of furries killing each other with spaceships for a game console that was already e-waste the year it came out, Haha.

There are tons of FOSS projects like GNU Hurd, Wine, XFCE, MATE, TDE and so on that need C/C++ developers, and here you are wasting your time on this, it's truly hilarious.

PS: I am a retired engineer for Matrox Video, I developed the software and drivers for the PG/SM series cards and the Studio video editing system, all of which were cutting edge in their day, Now cry as you won't be able to match my might by patching dumb old games.

**Comment by AlexanderCherniavsky** [comment]
There, I created PR #263 for you, maybe you can do something useful with your pathetic life by merging it? :)
